In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
# 레이블 인코딩
items= ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
encoder.transform(items)
# 새로 들어온 데이터는 fit을 하면 않된다.
# 기존의 데이터가 사라진다.
# 전체데이터 fit -> transform
# 한번만에 fit이 안 될 수도 있다.
# 이 경우 인코더 개체가 남아있어야한다.
# 변경만 해야한다.

# -> 추가해서 학습하는게 되지 않는다.
# 처음에 데이터 수집할 때에, 당연히 전체 모집단을 대표 할 수 있는 표본 집단 암을 전제로 한다.

labels = encoder.transform(items)


# fit() 딕션어리 생성 목록 추출
# transform() 데이터를 딕션어리 목록을 기반으로 변경

In [3]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [4]:
encoder.transform(['냉장고'])

array([1])

In [5]:
encoder.classes_
# 원래 무슨 데이터개체(의미)인지 볼 수 있다.

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [6]:
encoder.inverse_transform([1])
# 본래 무슨 데이터 개체인지 반환해준다.

array(['냉장고'], dtype='<U5')

In [7]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [37]:
 np.array(items).reshape(-1,1)

array([['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [9]:
# ONE-HOT 인코딩
items
items_t = np.array(items).reshape(-1,1)
items_l = [['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']]

In [10]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(items_t)
result = oh_encoder.transform(items_t)
result.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [12]:
oh_encoder.categories_

[array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype=object)]

In [13]:
oh_encoder.inverse_transform([[1.,0.,0.,0.,0.,0.]])

array([['TV']], dtype=object)

In [14]:
oh_encoder.transform([['냉장고']]).toarray()

array([[0., 1., 0., 0., 0., 0.]])

In [15]:
# 데이터 프레임에 원핫 인코딩 적용
import pandas as pd

In [16]:
df = pd.DataFrame({'item': ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [17]:
pd.get_dummies(df['item'])

TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

In [18]:
from sklearn.datasets import load_iris

In [19]:
iris = load_iris(as_frame=True)

In [20]:
iris.data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [21]:
iris.data.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [22]:
iris.data.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler = StandardScaler()
# 표준화
scaler.fit(iris.data)
iris_scaled = scaler.transform(iris.data)

In [25]:
iris_df = pd.DataFrame(iris_scaled)

In [26]:
iris_df.mean().round(5) #평균이 0으로 맞춰짐

0   -0.0
1   -0.0
2   -0.0
3   -0.0
dtype: float64

In [27]:
iris_df.var() #분산이 1로 맞춰짐

0    1.006711
1    1.006711
2    1.006711
3    1.006711
dtype: float64

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
# 정규화
scaler = MinMaxScaler()
scaler.fit(iris.data)
iris_scaled = scaler.transform(iris.data)

In [30]:
iris_df = pd.DataFrame(iris_scaled)
iris_df.min() # 최솟값이 0

0    0.0
1    0.0
2    0.0
3    0.0
dtype: float64

In [31]:
iris_df.max() # 최댓값이 1

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float64

In [32]:
# 정
train_array = np.arange(0,11).reshape(-1,1)
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [38]:
test_array = np.arange(0,6).reshape(-1,1)
train_array, test_array

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]))

In [34]:
#정규화
scaler = MinMaxScaler()
scaler.fit(train_array)
train_array_scaler = scaler.transform(train_array)
# transform으로 적용해야한다.

train_array

test_array_scaler = scaler.transform(test_array)
train_array_scaler, test_array_scaler


(array([[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9],
        [1. ]]),
 array([[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5]]))

In [35]:
# testscaler 의 스케일러를 유지 하여야 한다.
# fit을 하면 스케일러 기준값이 바뀌어 버린다.
scaler.fit(test_array)
test_array_scaler = scaler.transform(test_array)
test_array_scaler
# 값이 0~1 사이

array([[0. ],
       [0.2],
       [0.4],
       [0.6],
       [0.8],
       [1. ]])