In [1]:
import tensorflow as tf

In [2]:
tf.random.set_seed(777)

In [3]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
# 확률 경사 하강법 전체 데이터 대상이 아니라 일부만

from keras.losses import mse

In [4]:
# or 게이트 학습
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array(([0],[1],[1],[1]))


In [6]:
x.shape, y.shape

((4, 2), (4, 1))

In [ ]:
# 모델 생성 및 설정, 학습
model = Sequential()
model.add(Dense(1,input_shape=(2,),activation='linear'))

model.compile(optimizer=SGD(),
              loss = mse,
              metrics=['acc'])

model.fit(x,y,epochs=500)
# epochs 전체 데이터를 500번 학습

In [ ]:
model.get_weights()
# 모델이 학습한 뒤, 만든 가중치 확인인

[array([[0.49431458],
        [0.37552658]], dtype=float32), array([0.32719323], dtype=float32)]

In [ ]:
(0*0.49431458)+(0*0.37552658) + 0.32719323

0.32719323

In [ ]:
(1*0.49431458)+(0*0.37552658) + 0.32719323

0.82150781

In [ ]:
(1*0.49431458)+(1*0.37552658) + 0.32719323

1.19703439

In [ ]:
# and 게이트
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array(([0],[0],[0],[1]))

In [ ]:
model = Sequential()
model.add(Dense(1,input_shape=(2,),activation='linear'))
# 출력이 1개이고 입력에 2인 선형 함수
model.compile(optimizer=SGD(),
              loss = mse,
              metrics=['acc'])
# 옵티마이져(예측치와 실제값의 차이를 줄이는 방법으로)로 경사하강법, mse 값을 오차값으로, 평가지표로 accuracy를 설정
model.fit(x,y,epochs=500)
# epochs 전체 데이터를 500번 학습

In [ ]:
model.get_weights()

[array([[0.53026605],
        [0.40107936]], dtype=float32), array([-0.20928293], dtype=float32)]

In [ ]:
(0*0.53026605)+(0*0.40107936) -0.20928293

-0.20928293

In [ ]:
(0*0.53026605)+(1*0.40107936) -0.20928293

0.19179643

In [ ]:
(1*0.53026605)+(0*0.40107936) -0.20928293

0.32098312000000007

In [ ]:
(1*0.53026605)+(1*0.40107936) -0.20928293

0.7220624800000001

In [ ]:
# nand 게이트
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array(([1],[1],[1],[0]))

In [ ]:
model = Sequential()
model.add(Dense(1,input_shape=(2,),activation='linear'))

model.compile(optimizer=SGD(),
              loss = mse,
              metrics=['acc'])

model.fit(x,y,epochs=500)
# epochs 전체 데이터를 500번 학습

In [ ]:
model.get_weights()

[array([[-0.46928743],
        [-0.46345294]], dtype=float32), array([1.2101102], dtype=float32)]

In [ ]:
(0*-0.46928743)+(0*-0.46345294) + 1.2101102

1.2101102

In [ ]:
(1*-0.46928743)+(0*-0.46345294) + 1.2101102

0.7408227699999999

In [ ]:
(0*-0.46928743)+(1*-0.46345294) + 1.2101102

0.7466572599999999

In [ ]:
(1*-0.46928743)+(1*-0.46345294) + 1.2101102


0.27736982999999993

In [7]:
# xor 문제
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array(([0],[1],[1],[0]))


In [8]:
model = Sequential()
model.add(Dense(1,input_shape=(2,),activation='linear'))

model.compile(optimizer=SGD(),
              loss = mse,
              metrics=['acc'])

model.fit(x,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 647ms/step - loss: 0.9969 - acc: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 11ms/step - loss: 0.9642 - acc: 0.7500
Epoch 3/500
1/1 [==============================] - 0s 13ms/step - loss: 0.9334 - acc: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 12ms/step - loss: 0.9043 - acc: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 10ms/step - loss: 0.8770 - acc: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 15ms/step - loss: 0.8512 - acc: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 14ms/step - loss: 0.8270 - acc: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 11ms/step - loss: 0.8041 - acc: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7825 - acc: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7621 - acc: 0.7500
Epoch 11/500
1/1 [==============================] - 0s 17ms/step - lo

In [19]:
xor_weights= model.get_weights()
xor_weights

[array([[ 0.07334828],
        [-0.04543964]], dtype=float32), array([0.48344818], dtype=float32)]

In [27]:
0*xor_weights[0][0][0] + 0*xor_weights[0][1][0] +  xor_weights[1][0]

0.48344817757606506

In [28]:
0*xor_weights[0][0][0] + 1*xor_weights[0][1][0] +  xor_weights[1][0]

0.43800853937864304

In [29]:
1*xor_weights[0][0][0] + 0*xor_weights[0][1][0] +  xor_weights[1][0]

0.5567964613437653

In [30]:
1*xor_weights[0][0][0] + 1*xor_weights[0][1][0] +  xor_weights[1][0]

0.5113568231463432

In [31]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, RMSprop
from keras.losses import mse

In [32]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array(([0],[1],[1],[0]))

In [33]:
# 두개의 층으로 이루어진 모델 생성, 설정 , 학습
model = Sequential()
model.add(Dense(32,input_shape=(2,),activation='relu'))
# relu 함수 사용
model.add(Dense(1,activation='linear'))

model.compile(optimizer=SGD(),
              loss = mse,
              metrics=['acc'])

model.fit(x,y,epochs=500)
# epochs 전체 데이터를 500번 학습

Epoch 1/500
1/1 [==============================] - 0s 455ms/step - loss: 0.2956 - acc: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2844 - acc: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 15ms/step - loss: 0.2742 - acc: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 13ms/step - loss: 0.2650 - acc: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 10ms/step - loss: 0.2567 - acc: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 13ms/step - loss: 0.2492 - acc: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2423 - acc: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 15ms/step - loss: 0.2361 - acc: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 15ms/step - loss: 0.2306 - acc: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 0.2257 - acc: 0.5000
Epoch 11/500
1/1 [==============================] - 0s 9ms/step - los

In [35]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 32)                96        
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 129
Trainable params: 129
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.layers[0].get_weights()

[array([[-0.06608   ,  0.20491175,  0.16689928, -0.3274011 ,  0.19156973,
         -0.35073712, -0.11138612, -0.10482529, -0.3825389 ,  0.17342177,
         -0.14542747, -0.3261035 , -0.39077842, -0.3733599 , -0.22378738,
          0.08149557,  0.3171516 , -0.1617077 , -0.26905715, -0.21284367,
          0.38517192,  0.06301912,  0.12461597, -0.3685555 ,  0.12023587,
          0.32200393,  0.2108498 , -0.25348008,  0.25613597,  0.37875724,
         -0.39488956,  0.39521408],
        [-0.23520407, -0.0776373 ,  0.28446543, -0.30099633,  0.19404459,
         -0.3637126 , -0.0262236 , -0.13919908, -0.18181299, -0.17338397,
          0.14557111, -0.29327622, -0.29735368,  0.3732254 ,  0.41987172,
          0.23307355,  0.10312056, -0.29803523, -0.18244307,  0.21295518,
          0.10682046,  0.18963018,  0.33197314,  0.33353573,  0.27270496,
         -0.32186228,  0.37479505,  0.25344494, -0.25609818, -0.39681137,
          0.36983874, -0.39534745]], dtype=float32),
 array([ 0.0000000e+00,

In [34]:
model.get_weights

# 2개의 입력에 대한 총 64(32 배열 2개)개의 가중치와, 32개의 바이어스,

# 2개의 입력단 32개의 출력단

# 32개의 입력에 대한 32개의 가중치와, 1개의 바이어스

# 32개의 입력단 1개의 출력단


[array([[-0.06608   ,  0.20491175,  0.16689928, -0.3274011 ,  0.19156973,
         -0.35073712, -0.11138612, -0.10482529, -0.3825389 ,  0.17342177,
         -0.14542747, -0.3261035 , -0.39077842, -0.3733599 , -0.22378738,
          0.08149557,  0.3171516 , -0.1617077 , -0.26905715, -0.21284367,
          0.38517192,  0.06301912,  0.12461597, -0.3685555 ,  0.12023587,
          0.32200393,  0.2108498 , -0.25348008,  0.25613597,  0.37875724,
         -0.39488956,  0.39521408],
        [-0.23520407, -0.0776373 ,  0.28446543, -0.30099633,  0.19404459,
         -0.3637126 , -0.0262236 , -0.13919908, -0.18181299, -0.17338397,
          0.14557111, -0.29327622, -0.29735368,  0.3732254 ,  0.41987172,
          0.23307355,  0.10312056, -0.29803523, -0.18244307,  0.21295518,
          0.10682046,  0.18963018,  0.33197314,  0.33353573,  0.27270496,
         -0.32186228,  0.37479505,  0.25344494, -0.25609818, -0.39681137,
          0.36983874, -0.39534745]], dtype=float32),
 array([ 0.0000000e+00,

In [ ]:
model.evaluate(x)

1/1 [==============================] - 0s 90ms/step - loss: 0.0000e+00 - acc: 0.0000e+00


[0.0, 0.0]

In [ ]:
model.predict(x)

1/1 [==============================] - 0s 177ms/step


array([[0.21283409],
       [0.8134363 ],
       [0.87249714],
       [0.14701   ]], dtype=float32)